apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: utkarshvedksfinal 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: utkarshvedksfinal 
    spec:
      containers:
        - name: utkarshvedksfinal 
          image: k8spipeline.azurecr.io/utkarshvedksfinal
          ports:
          - containerPort: 80